### ISSUE TITLE
question about Std_String

### ISSUE THREAD

**Issue by xPrimeMC** [zhkj-liuxiaohua/BDSNetRunner#12]
Helo, I'm trying to pass a string to a c++ function with dlsym but I'm not sure how to initialize and construct a Std_String, there's no function in StrTool and I would like some help on this matter, thanks

**Comment by zhkj-liuxiaohua** [comment]
https://docs.microsoft.com/en-us/previous-versions/aa720411(v=vs.71)?redirectedfrom=MSDN
C#:
public static extern bool OpenA([In, MarshalAs(UnmanagedType.LPStr)] path);
C++:
bool __declspec( dllexport ) OpenA(std::string file);

**Comment by xPrimeMC** [comment]
how do i get this to work with a native rva function using MCCSAPI::dlsym?

**Comment by xPrimeMC** [comment]
something like this https://github.com/zhkj-liuxiaohua/BDSNetRunner/blob/master/CSRDemo/Hook.cs#L134

**Comment by LazuliKao** [comment]
**build a C++ DLL as a bridge ( I am not sure if it is feasible**
include an exported function which can create std::string from `byte[]`(which can be created in C#), and the result is an address of the std::string

use `[DllImport("xxx.dll")]` in C# to Invoke the function so that can get an Intptr of new string, this Intptr could be put into the delegate from `dlsym`

**Comment by zhkj-liuxiaohua** [comment]
I take a testcase about call CPPCALL to construct a std::string in C#:
`class SymCall
    {
        MCCSAPI mapi;
        public SymCall(MCCSAPI api)
        {
            mapi = api;
        }
        delegate IntPtr CPPCALL_ASSIGN(IntPtr s, byte[] src, ulong size);
        delegate IntPtr CPPCALL_ALLOC(uint size);
        delegate void CPPCALL_DEALLOC(IntPtr s);
        delegate void CPPCALL_SETNAME(IntPtr p, IntPtr s);
        public void setPlayerName(IntPtr player, string name)
        {
            CPPCALL_ASSIGN callstdstringconstructor = null;
            CPPCALL_ALLOC callstdalloc = null;
            CPPCALL_DEALLOC freestdstring = null;
            CPPCALL_SETNAME callsetname = null;
            switch (mapi.VERSION)
            {
                case "1.16.201.3":
                    callstdstringconstructor = Marshal.GetDelegateForFunctionPointer<CPPCALL_ASSIGN>(mapi.dlsym(0x0070D000));
                    callstdalloc = Marshal.GetDelegateForFunctionPointer<CPPCALL_ALLOC>(mapi.dlsym(0x0070CF40));
                    freestdstring = Marshal.GetDelegateForFunctionPointer<CPPCALL_DEALLOC>(mapi.dlsym(0x0070CE90));
                    callsetname = Marshal.GetDelegateForFunctionPointer<CPPCALL_SETNAME>(mapi.dlsym(0x00F5F660));
                    break;
            }
            if (callstdstringconstructor != null)
            {
                IntPtr s = Marshal.AllocHGlobal(32);                // std::string *s = new std::string();

                Marshal.Copy(new byte[32], 0, s, 32);               // memset(s, 0, sieof(std::string));

                Marshal.WriteIntPtr(s, callstdalloc(0x1000));       // IDA std::_Allocate<

                Marshal.WriteInt64(s + 24, 0x1000);
                var ss = Encoding.UTF8.GetBytes(name);
                callstdstringconstructor(s, ss, (ulong)ss.Length);  // IDA std::allocator<char>>::assign

                callsetname(player, s);                             // IDA Player::setName

                freestdstring(s);                                   // IDA std::allocator<char> >::_Tidy_deallocate

                Marshal.FreeHGlobal(s);
            } else
            {
                Console.WriteLine("[TEST] 版本不符。");
            }
        }
    }`
Hopes can help you.

**Comment by zhkj-liuxiaohua** [comment]
The Std_String is a read-only struct for return data used for [BDSNetRunner.dll]. No need to construct. Use `Marshal.AllocHGlobal` instead.
