### ISSUE TITLE
玩家丢出物品事件拦截后，可能无法还原物品

### ISSUE THREAD

**Issue by LazuliKao** [zhkj-liuxiaohua/BDSNetRunner#14]
onDropItem监听，return false拦截后

复现情境：拦截onDropItem监听，Q键丢出物品会消失
（不过背包界面拖拽丢出，拦截后能正常还原物品）
理想情况：拦截onDropItem监听，物品能正常还原
试图修复：尝试在拦截后调用addItem，但是反而会刷物品
![image](https://user-images.githubusercontent.com/46601807/121183472-ae4f1500-c896-11eb-8656-5ecf38c4c973.png)

**Comment by zhkj-liuxiaohua** [comment]
这个没法解决，建议联系社区贡献者讨论相关改进方案 @kengwang

**Comment by LazuliKao** [comment]
也许可以改成在处理网络包的时候就拦截，不过也有可能有一样的bug，如果能的话每次更新都得找偏移

**Comment by cngege** [comment]
你上面发的那张图片 将第一行给玩家物品去掉，只刷新玩家背包看看行不行

**Comment by LazuliKao** [comment]
> 你上面发的那张图片 将第一行给玩家物品去掉，只刷新玩家背包看看行不行

试了，还是会消失

**Comment by LazuliKao** [comment]
方法`?executeFull@InventoryTransaction@@QEBA?AW4InventoryTransactionError@@AEAVPlayer@@_N@Z`返回false可拦截快捷键丢出物品，但包含其他操作，Player::drop方法是在InventoryTransaction::executeFull方法内通过偏移直接执行的，无法判断，所以issue关闭
