### ISSUE TITLE
请添加一个函数，使C#插件可以直接操作计分板

### ISSUE THREAD

**Issue by SnowPea8072** [zhkj-liuxiaohua/BDSNetRunner#3]
由于runcmd的返回值只有执行是否成功，而在做需要与玩家互动的插件时，极其需要testfor、execute等命令的返回值，考虑到JSR可能没有办法截取到这些命令的返回值，因此希望能够定义一个函数，使C#插件可以直接操作到计分板，以此间接操作testfor、execute等命令（主要原因是部分的C++插件已经有操作计分板的案例），当然，直接获取testfor、execute等命令的返回值更好。
希望可以采纳此建议！

**Comment by zhkj-liuxiaohua** [comment]
已由社区贡献添加了 getscoreboard 函数。详见 CSRDemo/BDS/MCCSAPI.cs
如有更好的改进方案，欢迎自行发起pull request进行平台的建设。
