### ISSUE TITLE
Crashes Under Wine

### ISSUE THREAD

**Issue by substicious** [zhkj-liuxiaohua/BDSNetRunner#6]
Hi,

Before the latest MC update Net runner worked under wine but the latest BDS and NetRunner crashes wine. Has anything changed for NETRunner not to work on WINE

Sub

**Comment by zhkj-liuxiaohua** [comment]
很抱歉，目前没有针对linux环境的开发设计目标，请使用win10或win server2016以上版本的操作系统环境运行此插件。不予处理。
