### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by krusalovorg** [zhkj-liuxiaohua/BDSNetRunner#8]
![image](https://user-images.githubusercontent.com/70585437/102306302-5be20b00-3f7b-11eb-908c-6c6cee48607c.png)
![image](https://user-images.githubusercontent.com/70585437/102306306-5f759200-3f7b-11eb-945d-688cb30b840f.png)
![image](https://user-images.githubusercontent.com/70585437/102306315-62708280-3f7b-11eb-9728-eda8a79bde9b.png)
Can't compile BDSNetRUNNER source code
How do I fix these errors?

**Comment by zhkj-liuxiaohua** [comment]
How to compile: unzip [MCBDS插件开发助手.zip] in the project directory, and use [MCBDS插件开发助手.exe] to export the corresponding pdb file [bedrock_server.pdb] of MC server header file [RVAs.hpp] replace the original engineering documents.

Note: you need use the VisualStudio2019(last nearby version:16.8.3) release x64 to compile it, but this code table applied as win1.16.100.1 BDS and not test.  Not fix.
