### ISSUE TITLE
添加某些可能需要的 API

### ISSUE THREAD

**Issue by kengwang** [zhkj-liuxiaohua/BDSNetRunner#9]
> 这不是一篇请求添加Issue,而是会写一些具体的 API ,希望作者可以将他实现出来
> 我会以 Comment 的形式持续提出一些可使用的API接口

部分API源自于本人早期开发项目 [FutrueCraftServer/BDSPlugin](https://github.com/FuturecraftServer/BDSPlugin)

**Comment by kengwang** [comment]
### 修改服务器的 MOTD

> 函数原型: public: void __cdecl ServerNetworkHandler::allowIncomingConnections(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,bool) __ptr64
> 符号: `?allowIncomingConnections@ServerNetworkHandler@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z`
> RVA代码: MSSYM_MD5_21204897709106ba1d290df17fead479

相关说明: 
使用方法: SYMCALL调用
参数表:
* string 服务器的motd
* bool 是否公开服务器

下面为可能的代码实现
```
SYMCALL(void,
		MSSYM_MD5_21204897709106ba1d290df17fead479,
		p_ServerNetworkHandle, &motd, true);
```

**Comment by kengwang** [comment]
## 活塞推方块
> [原型] `private: bool __cdecl PistonBlockActor::_attachedBlockWalker(class BlockSource & __ptr64,class BlockPos const & __ptr64,unsigned char,unsigned char) __ptr64`
> 0x00F1D240	`?_attachedBlockWalker@PistonBlockActor@@AEAA_NAEAVBlockSource@@AEBVBlockPos@@EE@Z`

使用方法: THook监听
相关说明:
_this 为活塞方块
BlockPos参数为被推的方块的坐标
返回值为是否可以推动

**Comment by kengwang** [comment]
### 玩家取物品展示框物品
> [原型] `public: virtual bool __cdecl ItemFrameBlock::playerWillDestroy(class Player & __ptr64,class BlockPos const & __ptr64,class Block const & __ptr64)const __ptr64`
> 0x00FAF180	`?playerWillDestroy@ItemFrameBlock@@UEBA_NAEAVPlayer@@AEBVBlockPos@@AEBVBlock@@@Z`

使用方法: THook监听
相关说明:
this通过换取到actor再指针+232就可以获取物品了

**Comment by kengwang** [comment]
## 箱子系列 (我之前开发过锁箱子,这些函数够拿来锁箱子了)
### 箱子合并为大箱子
> [原型] `public: void __cdecl ChestBlockActor::pairWith(class ChestBlockActor * __ptr64,bool) __ptr64`
> 0x00F04650	`?pairWith@ChestBlockActor@@QEAAXPEAV1@_N@Z`

使用方法: THook监听
相关说明: _this为主箱子,传入的为第二个箱子,我依稀记得好像会调用两次(因为每个箱子判断一次) 
假如说允许合并的话调用original,不允许的话直接返回void


### 箱子解除合并
(此方法有些问题!)
> [原型] `public: void __cdecl ChestBlockActor::unpair(class BlockSource & __ptr64) __ptr64`
> 0x00F04860	`?unpair@ChestBlockActor@@QEAAXAEAVBlockSource@@@Z`

使用方法: THook监听
相关说明: 假如允许 的话就original,不允许直接void

**Comment by kengwang** [comment]
### 生物生成
> [原型] `public: virtual bool __cdecl Mob::checkSpawnRules(bool) __ptr64`
> 0x00D47E30	`?checkSpawnRules@Mob@@UEAA_N_N@Z`

使用方法: THook监听
相关说明: 传入的mob参数为要生成的实体,他也是有坐标等参数的哦~
假如允许生成返回true,不允许返回false
不过建议假如允许的话看看original是否允许

**Comment by kengwang** [comment]
差不多我之前的东西就这么多了吧,可能有些没整理出来的,那多半是没看到.
因为改代码的话稍微有点

**Comment by kengwang** [comment]
## 附魔相关
### 物品是否附魔
> [原型] `public: bool __cdecl ItemStackBase::isEnchanted(void)const __ptr64`
> 0x00E5F530	`?isEnchanted@ItemStackBase@@QEBA_NXZ`

返回T/F为当前ItemStack物品是否附魔

### 物品附魔等级
```
[原型] public: static int __cdecl EnchantUtils::getEnchantLevel(enum Enchant::Type,class ItemStackBase const & __ptr64)
0x00E3F500	?getEnchantLevel@EnchantUtils@@SAHW4Type@Enchant@@AEBVItemStackBase@@@Z
```
EnchantType的话可以参考 mc的wiki

**Comment by kengwang** [comment]
### 跨服传送 (灵感来自BDX)
(以下代码为我之前项目的代码,可能需要改改
```
//跨服传送
	void transferServer(std::string server, int port) {
		WBStream ws;
		ws.apply(VarUInt(server.size()));
		ws.write(server.c_str(), server.size());
		ws.apply(VarUInt(port));
		MyPkt<0x55, false> guipk{ ws.data };
		SYMCALL(VA, MSSYM_B1QE17sendNetworkPacketB1AE12ServerPlayerB2AAE15UEBAXAEAVPacketB3AAAA1Z,
			this, &guipk); //this是player
	}
```

**Comment by zhkj-liuxiaohua** [comment]
1. 关于**附魔**：由于目前CSR还没有深入到物品组件，要使用相关api需要构建较多代码，另商业版已包含物品导入导出功能，利用nbt结构也可快速读写附魔内容。暂不处理。
2. 关于**箱子解除合并**：该事件无法拦截，暂时想不到有什么特殊应用场景，暂不处理。
3. 关于**玩家取物品展示框物品**：该事件点位不正确，无法截获取物品内容这一过程（实测win10版无效），仅对展示框这一方块的破坏具有拦截效果。暂不处理。

**Comment by kengwang** [comment]
麻烦大佬了，之后我就直接pr了吧。
因为之前不知道该如何contribute，就只好发了个Issue
